Version = 1;
Make: "ZTE";
Model: "Blade S6";

Rear: {
    SensorDriver: "imx214";
    BridgeDriver: "qcom-camss";

    Modes: (
        {
            Width: 4208;
            Height: 3120;
            Rate: 30;
            Format: "RGGB10p";
            Rotate: 270;

            Pipeline: (
                {Type: "Link", From: "msm_csiphy0", FromPad: 1, To: "msm_csid0", ToPad: 0},
                {Type: "Link", From: "msm_csid0", FromPad: 1, To: "msm_ispif0", ToPad: 0},
                {Type: "Link", From: "msm_ispif0", FromPad: 1, To: "msm_vfe0_rdi0", ToPad: 0},
                {Type: "Mode", Entity: "imx214"},
                {Type: "Mode", Entity: "msm_csiphy0"},
                {Type: "Mode", Entity: "msm_csid0"},
                {Type: "Mode", Entity: "msm_ispif0"},
                {Type: "Mode", Entity: "msm_vfe0_rdi0"}
            );
        },
        {
            Width: 2104;
            Height: 1560;
            Rate: 30;
            Format: "RGGB10p";
            Rotate: 270;

            Pipeline: (
                {Type: "Link", From: "msm_csiphy0", FromPad: 1, To: "msm_csid0", ToPad: 0},
                {Type: "Link", From: "msm_csid0", FromPad: 1, To: "msm_ispif0", ToPad: 0},
                {Type: "Link", From: "msm_ispif0", FromPad: 1, To: "msm_vfe0_rdi0", ToPad: 0},
                {Type: "Mode", Entity: "imx214"},
                {Type: "Mode", Entity: "msm_csiphy0"},
                {Type: "Mode", Entity: "msm_csid0"},
                {Type: "Mode", Entity: "msm_ispif0"},
                {Type: "Mode", Entity: "msm_vfe0_rdi0"}
            );
        },
        {
            Width: 1920;
            Height: 1080;
            Rate: 30;
            Format: "RGGB10p";
            Rotate: 270;

            Pipeline: (
                {Type: "Link", From: "msm_csiphy0", FromPad: 1, To: "msm_csid0", ToPad: 0},
                {Type: "Link", From: "msm_csid0", FromPad: 1, To: "msm_ispif0", ToPad: 0},
                {Type: "Link", From: "msm_ispif0", FromPad: 1, To: "msm_vfe0_rdi0", ToPad: 0},
                {Type: "Mode", Entity: "imx214"},
                {Type: "Mode", Entity: "msm_csiphy0"},
                {Type: "Mode", Entity: "msm_csid0"},
                {Type: "Mode", Entity: "msm_ispif0"},
                {Type: "Mode", Entity: "msm_vfe0_rdi0"}
            );
        }
    );
};

Front: {
    SensorDriver: "s5k5e2";
    BridgeDriver: "qcom-camss";

    Modes: (
        {
            Width: 2560;
            Height: 1920;
            Rate: 30;
            Format: "GRBG10p";
            Rotate: 270;
            Mirror: true;

            Pipeline: (
                {Type: "Link", From: "msm_csiphy1", FromPad: 1, To: "msm_csid0", ToPad: 0},
                {Type: "Link", From: "msm_csid0", FromPad: 1, To: "msm_ispif0", ToPad: 0},
                {Type: "Link", From: "msm_ispif0", FromPad: 1, To: "msm_vfe0_rdi0", ToPad: 0},
                {Type: "Mode", Entity: "s5k5e2"},
                {Type: "Mode", Entity: "msm_csiphy1"},
                {Type: "Mode", Entity: "msm_csid0"},
                {Type: "Mode", Entity: "msm_ispif0"},
                {Type: "Mode", Entity: "msm_vfe0_rdi0"}
            );
        },
        {
            Width: 1280;
            Height: 960;
            Rate: 30;
            Format: "GRBG10p";
            Rotate: 270;
            Mirror: true;

            Pipeline: (
                {Type: "Link", From: "msm_csiphy1", FromPad: 1, To: "msm_csid0", ToPad: 0},
                {Type: "Link", From: "msm_csid0", FromPad: 1, To: "msm_ispif0", ToPad: 0},
                {Type: "Link", From: "msm_ispif0", FromPad: 1, To: "msm_vfe0_rdi0", ToPad: 0},
                {Type: "Mode", Entity: "s5k5e2"},
                {Type: "Mode", Entity: "msm_csiphy1"},
                {Type: "Mode", Entity: "msm_csid0"},
                {Type: "Mode", Entity: "msm_ispif0"},
                {Type: "Mode", Entity: "msm_vfe0_rdi0"}
            );
        }
    );
};
